###
GET http://localhost:5000/api/users

###
POST http://localhost:5000/api/dispositivos
Content-Type: application/json

{
    "numeroSerie": "Eliminar",
    "modelo":"qwert",
    "marca": "qwdf",
    "tipo": "Smartphone",
    "memoria": "128",
    "procesador": "hola",
    "resolucion":"1080",
    "precio":1000
}

###
GET http://localhost:5000/api/dispositivos

###
DELETE http://localhost:5000/api/users/60441c9a38ab18207cc23d86


###
PUT http://localhost:5000/api/dispositivos/60122dc3d2e3e11640fa06ee
Content-Type: application/json

{
    "numeroSerie": "ActualizadoJAJA"

}
###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "email": "LeonelCI@gmail.com",
    "password":"password"
}

###
POST http://localhost:5000/api/users/signIn
Content-Type: application/json

{
    "email": "LeonelCI@gmail.com",
    "password":"qwer"
}