###
GET http://localhost:5000/api/users

###
GET http://localhost:5000/api/pedidos

###
POST http://localhost:5000/api/dispositivos
Content-Type: application/json

{
    "numeroSerie": "Eliminar",
    "modelo":"qwert",
    "marca": "qwdf",
    "tipo": "Smartphone",
    "memoria": "128",
    "procesador": "hola",
    "resolucion":"1080",
    "precio":1000
}

###
GET http://localhost:5000/api/dispositivos

###
DELETE http://localhost:5000/api/users/60441c9a38ab18207cc23d86


###
PUT http://localhost:5000/api/dispositivos/604a567dc6a7b81680bc2df1
Content-Type: application/json

{
    "numeroSerie": "ActualizadoJAJA"

}
###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "email": "LeonelCI@gmail.com",
    "password":"password"
}

###
POST http://localhost:5000/api/users/signIn
Content-Type: application/json

{
    "email": "LeonelCI@gmail.com",
    "password":"qwer"
}


###
POST http://localhost:5000/api/pedidos 
Content-Type: application/json

{
"cantidad": 5, 
"total": 458, 
"fecha_p": "03-10-2021", 
"fecha_e": "03-15-2021", 
"dispositivo": "6046a9ed5181b70314f6d352", 
"user": "60441ce038ab18207cc23d87"
}